# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\cat_eye\daily_sentence\untitled1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont
import import_text as im_te
import random

#文本接口
textdic = im_te.read_file_to_dict('sentence.md')
#i = int(input("please enter the sequence of the sentence."))
sen_num = len(textdic)
i = random.randint(1, sen_num)

#字体设置
font1 = QFont()
font1.setFamily('微软雅黑')
font1.setBold(True)
font1.setPixelSize(30)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        #窗口设置
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 1200)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setStyleSheet('background-color: #FFFFFF;')


        #左上角日期设置
        self.date = QtWidgets.QLabel(self.centralwidget)
        self.date.setGeometry(QtCore.QRect(100, 100, 320, 320))
        self.date.setText("Date")
        self.date.setObjectName("date")
        self.date.setAlignment(QtCore.Qt.AlignCenter)
        self.date.setStyleSheet('border: 3px solid #000000;')

        #左侧中间按钮
        self.change_but = QtWidgets.QPushButton(self.centralwidget)
        self.change_but.setGeometry(QtCore.QRect(135, 500, 250, 150))
        self.change_but.setObjectName("change_but")
        self.change_but.clicked.connect(self.change_sequence)

        #文本框设置
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(500, 80, 1050, 700))
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))

        self.label.setFont(font1)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label.setStyleSheet('background-color: #EFF9FF; border: 10px solid #CCCCCC;border-radius: 15px;padding: 5px;margin: 10px;')


        #左下角收藏夹按钮
        self.star = QtWidgets.QPushButton(self.centralwidget)
        self.star.setGeometry(QtCore.QRect(70, 750, 380, 380))
        self.star.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\cat_eye\\daily_sentence\\pictures/star.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.star.setIcon(icon)
        self.star.setIconSize(QtCore.QSize(380, 380))
        self.star.setObjectName("star")
        self.star.setStyleSheet('border: 2px solid #CCCCCC;border-radius: 180px;padding: 5px;margin: 10px;') 
        self.star.setCheckable(True)
        self.star.setAutoExclusive(True)
        self.star.clicked.connect(self.clickStar)


        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    #星星按钮的变化
    def clickStar(self):
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\cat_eye\\daily_sentence\\pictures/star.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("d:\\cat_eye\\daily_sentence\\pictures/star2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        if self.star.isChecked:
            self.star.setIcon(icon)
            self.star.setIconSize(QtCore.QSize(380, 380))
        else:
            self.star.setIcon(icon2)
            self.star.setIconSize(QtCore.QSize(380, 380))
        self.star.isChecked = not self.star.isChecked

    #change按钮按下后随机
    def change_sequence(self):
        i = random.randint(1, sen_num)
        self.label.setText('<p style="line-height:60px;">{}</p>'.format(textdic[i]))
    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.change_but.setText(_translate("MainWindow", "Change"))
        self.label.setText(_translate("MainWindow", '<p style="line-height:60px;">{}</p>'.format(textdic[i])))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())