# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\cat_eye\daily_sentence\untitled1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, -20, 801, 601))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("d:\\cat_eye\\daily_sentence\\pictures/background.png"))
        self.background.setObjectName("background")
        self.date = QtWidgets.QLabel(self.centralwidget)
        self.date.setGeometry(QtCore.QRect(40, 30, 161, 161))
        self.date.setText("")
        self.date.setPixmap(QtGui.QPixmap("d:\\cat_eye\\daily_sentence\\pictures/date.png"))
        self.date.setObjectName("date")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 230, 131, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 40, 511, 321))
        self.label.setObjectName("label")
        self.star = QtWidgets.QPushButton(self.centralwidget)
        self.star.setGeometry(QtCore.QRect(30, 370, 161, 161))
        self.star.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\cat_eye\\daily_sentence\\pictures/star.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.star.setIcon(icon)
        self.star.setIconSize(QtCore.QSize(160, 160))
        self.star.setObjectName("star")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.background.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">这是一个文本框</p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
